# -*- coding: utf-8 -*-

#@author: Ankit Singh
Main: 
    Input : 'C:\Users\310247467\Desktop\learn\padestriandetection\Input\'
    Output: 'C:\Users\310247467\Desktop\learn\padestriandetection\Output\'

FileType: 
    - jpg
    - png
    - ppm
