# -*- coding: utf-8 -*-

#@author: Ankit Singh
Main: 
    Input:
        positive: 'G:\git\padestriandetection\Input\pos\'
        Negative: 'G:\git\padestriandetection\Input\neg\'       
    Output: 'G:\git\padestriandetection\Output\'

FileType: 
- png
- ppm
